name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Upload vendor folder
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor

  tests:
    name: Run Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer
      - name: Download vendor folder
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - name: Fix permissions
        run: chmod +x vendor/bin/*
      - run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml tests/AppTest --display-deprecations --display-notices --display-warnings --coverage-text